### ISSUE TITLE
segfault ydotoold

### ISSUE THREAD

**Issue by hooltoo** [ReimuNotMoe/ydotool#103]
After two keys sended ydotoold SIGSEGV.

**debian testing (bullseye)
ydotool (0.1.8-3)
ydotoold (0.1.8-3)**

```
Feb 15 18:04:37 titus kernel: ydotoold[500290]: segfault at 0 ip 0000000000000000 sp 00007ffec6ba7428 error 14 in ydotoold[400000+1000]
Feb 15 18:04:37 titus kernel: Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
```

```
~# gdb -batch -n -ex 'set pagination off' -ex run -ex bt -ex 'bt full' -ex 'thread apply all bt full' --args ydotoold
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
ydotoold: listening on socket /tmp/.ydotool_socket
ydotoold: accepted client
[New Thread 0x7ffff7ff8700 (LWP 502215)]

Thread 1 "ydotoold" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
#0  0x0000000000000000 in ?? ()
#1  0x0000000000478571 in std::thread::detach() ()
#2  0x0000000000404574 in main (argc=<optimized out>, argv=<optimized out>) at ./Daemon/ydotoold.cpp:82
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x0000000000478571 in std::thread::detach() ()
No symbol table info available.
#2  0x0000000000404574 in main (argc=<optimized out>, argv=<optimized out>) at ./Daemon/ydotoold.cpp:82
        fd_client = 5
        thd = {_M_id = {_M_thread = 140737354106624}}
        path_socket = "/tmp/.ydotool_socket"
        fd_listener = 3
        addr = {sun_family = 1, sun_path = "/tmp/.ydotool_socket", '\000' <repeats 87 times>}

Thread 2 (Thread 0x7ffff7ff8700 (LWP 502215) "ydotoold"):
#0  __libc_recv (flags=<optimized out>, len=8, buf=0x7ffff7ff8270, fd=5) at ../sysdeps/unix/sysv/linux/recv.c:28
        resultvar = 18446744073709551104
        sc_cancel_oldtype = 0
        __value = <optimized out>
        __arg6 = <optimized out>
        __arg2 = <optimized out>
        _a3 = <optimized out>
        resultvar = <optimized out>
        resultvar = <optimized out>
        __arg3 = <optimized out>
        _a4 = <optimized out>
        sc_ret = <optimized out>
        __arg4 = <optimized out>
        _a5 = <optimized out>
        _a1 = <optimized out>
        __arg5 = <optimized out>
        __arg1 = <optimized out>
        _a6 = <optimized out>
        _a2 = <optimized out>
#1  __libc_recv (fd=fd@entry=5, buf=buf@entry=0x7ffff7ff8270, len=len@entry=8, flags=flags@entry=256) at ../sysdeps/unix/sysv/linux/recv.c:23
No locals.
#2  0x00000000004052c5 in recv (__flags=256, __n=8, __buf=0x7ffff7ff8270, __fd=5) at /usr/include/x86_64-linux-gnu/bits/socket2.h:44
No locals.
#3  client_handler (fd=5) at ./Daemon/ydotoold.cpp:34
        rc = <optimized out>
        buf = {type = 0, code = 0, value = 0}
#4  0x0000000000478330 in execute_native_thread_routine ()
No symbol table info available.
#5  0x0000000000406b17 in start_thread (arg=<optimized out>) at pthread_create.c:477
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140737354106624, -4718666658438785671, 140737488349710, 140737488349711, 140737354105728, 8396800,                                                                                                                                                                       4718649068300457337, -4718667209453546119}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0                                                                                                                                                                      }}}
        not_first_call = 0
#6  0x0000000000519b1f in clone ()
No symbol table info available.

Thread 1 (Thread 0x5ce380 (LWP 502187) "ydotoold"):
#0  0x0000000000000000 in ?? ()
No symbol table info available.
#1  0x0000000000478571 in std::thread::detach() ()
No symbol table info available.
#2  0x0000000000404574 in main (argc=<optimized out>, argv=<optimized out>) at ./Daemon/ydotoold.cpp:82
        fd_client = 5
        thd = {_M_id = {_M_thread = 140737354106624}}
        path_socket = "/tmp/.ydotool_socket"
        fd_listener = 3
        addr = {sun_family = 1, sun_path = "/tmp/.ydotool_socket", '\000' <repeats 87 times>}
```
```


~# gdb -batch -n -ex 'set pagination off' -ex run -ex bt -ex 'bt full' -ex 'thread apply all bt full' --args ydotool key Alt+Shift+q                                                                                                                                                                              [Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
ydotool: notice: Using ydotoold backend

Program received signal SIGPIPE, Broken pipe.
0x0000000000452edc in __libc_send (fd=3, buf=buf@entry=0x7fffffffe730, len=len@entry=8, flags=flags@entry=0) at ../sysdeps/unix/sysv/linux/send.c:2                                                                                                                                                                          8
28      ../sysdeps/unix/sysv/linux/send.c: No such file or directory.
#0  0x0000000000452edc in __libc_send (fd=3, buf=buf@entry=0x7fffffffe730, len=len@entry=8, flags=flags@entry=0) at ../sysdeps/unix/sysv/linux/send                                                                                                                                                                          .c:28
#1  0x000000000040f417 in socket_callback (type=<optimized out>, code=<optimized out>, val=<optimized out>, userp=<optimized out>) at ./Client/ydot                                                                                                                                                                          ool.cpp:81
#2  0x00000000004545a4 in uInputPlus::uInput::Emit(unsigned short, unsigned short, int) const ()
#3  0x000000000045460e in uInputPlus::uInput::SendKey(unsigned short, unsigned int, bool) const ()
#4  0x000000000041b2ea in ydotool::Tools::Key::EmitKeyCodes (this=this@entry=0x646220, key_delay=key_delay@entry=100, list_keycodes=...) at ./Tools                                                                                                                                                                          /Key/Key.cpp:101
#5  0x000000000041c6d2 in ydotool::Tools::Key::Exec (this=0x646220, argc=2, argv=<optimized out>) at ./Tools/Key/Key.cpp:204
#6  0x00000000004098f3 in main (argc=3, argv=0x7fffffffeca8) at ./Client/ydotool.cpp:136
#0  0x0000000000452edc in __libc_send (fd=3, buf=buf@entry=0x7fffffffe730, len=len@entry=8, flags=flags@entry=0) at ../sysdeps/unix/sysv/linux/send                                                                                                                                                                          .c:28
No locals.
#1  0x000000000040f417 in socket_callback (type=<optimized out>, code=<optimized out>, val=<optimized out>, userp=<optimized out>) at ./Client/ydot                                                                                                                                                                          ool.cpp:81
        buf = {type = 1, code = 56, value = 1}
        fd = <optimized out>
#2  0x00000000004545a4 in uInputPlus::uInput::Emit(unsigned short, unsigned short, int) const ()
No symbol table info available.
#3  0x000000000045460e in uInputPlus::uInput::SendKey(unsigned short, unsigned int, bool) const ()
No symbol table info available.
#4  0x000000000041b2ea in ydotool::Tools::Key::EmitKeyCodes (this=this@entry=0x646220, key_delay=key_delay@entry=100, list_keycodes=...) at ./Tools                                                                                                                                                                          /Key/Key.cpp:101
        it_m = @0x645e80: 56
        __for_range = @0x645ea0: {<std::_Vector_base<int, std::allocator<int> >> = {_M_impl = {<std::allocator<int>> = {<__gnu_cxx::new_allocator<i                                                                                                                                                                          nt>> = {<No data fields>}, <No data fields>}, <std::_Vector_base<int, std::allocator<int> >::_Vector_impl_data> = {_M_start = 0x645e80, _M_finish =                                                                                                                                                                           0x645e8c, _M_end_of_storage = 0x645e8c}, <No data fields>}}, <No data fields>}
        __for_begin = {_M_current = <optimized out>}
        __for_end = {_M_current = <optimized out>}
        it = @0x645ea0: {<std::_Vector_base<int, std::allocator<int> >> = {_M_impl = {<std::allocator<int>> = {<__gnu_cxx::new_allocator<int>> = {<                                                                                                                                                                          No data fields>}, <No data fields>}, <std::_Vector_base<int, std::allocator<int> >::_Vector_impl_data> = {_M_start = 0x645e80, _M_finish = 0x645e8c                                                                                                                                                                          , _M_end_of_storage = 0x645e8c}, <No data fields>}}, <No data fields>}
        __for_range = @0x7fffffffe850: {<std::_Vector_base<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<i                                                                                                                                                                          nt> > > >> = {_M_impl = {<std::allocator<std::vector<int, std::allocator<int> > >> = {<__gnu_cxx::new_allocator<std::vector<int, std::allocator<int                                                                                                                                                                          > > >> = {<No data fields>}, <No data fields>}, <std::_Vector_base<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::all                                                                                                                                                                          ocator<int> > > >::_Vector_impl_data> = {_M_start = 0x645ea0, _M_finish = 0x645eb8, _M_end_of_storage = 0x645eb8}, <No data fields>}}, <No data fie                                                                                                                                                                          lds>}
        __for_begin = {_M_current = <optimized out>}
        __for_end = {_M_current = <optimized out>}
        sleep_time = 50000
#5  0x000000000041c6d2 in ydotool::Tools::Key::Exec (this=0x646220, argc=2, argv=<optimized out>) at ./Tools/Key/Key.cpp:204
        time_delay = 100
        time_keydelay = <optimized out>
        time_repdelay = <optimized out>
        repeats = 0
        file_path = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fiel                                                                                                                                                                          ds>}, <No data fields>}, _M_p = 0x7fffffffe950 ""}, _M_string_length = 0, {_M_local_buf = "\000EL_Z\000\000\000\022\001\000\000\023\001\000", _M_al                                                                                                                                                                          located_capacity = 388145890560}}
        extra_args = {<std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx                                                                                                                                                                          11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {_M_impl = {<std::allocator<std::__cxx11::basic_string<char, std::char                                                                                                                                                                          _traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>                                                                                                                                                                           > >> = {<No data fields>}, <No data fields>}, <std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >,                                                                                                                                                                           std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Vector_impl_data> = {_M_start = 0x646730, _M_f                                                                                                                                                                          inish = 0x646750, _M_end_of_storage = 0x646750}, <No data fields>}}, <No data fields>}
        keycodes = {<std::_Vector_base<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >> = {_M_imp                                                                                                                                                                          l = {<std::allocator<std::vector<int, std::allocator<int> > >> = {<__gnu_cxx::new_allocator<std::vector<int, std::allocator<int> > >> = {<No data f                                                                                                                                                                          ields>}, <No data fields>}, <std::_Vector_base<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >::_                                                                                                                                                                          Vector_impl_data> = {_M_start = 0x645ea0, _M_finish = 0x645eb8, _M_end_of_storage = 0x645eb8}, <No data fields>}}, <No data fields>}
#6  0x00000000004098f3 in main (argc=3, argv=0x7fffffffeca8) at ./Client/ydotool.cpp:136
        library_path = <synthetic pointer>
        it_cmd = {<std::__detail::_Node_iterator_base<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > con                                                                                                                                                                          st, void*>, true>> = {_M_cur = <optimized out>}, <No data fields>}
        instance = {<std::__shared_ptr<ydotool::Instance, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<ydotool::Instance, (__gnu_cxx::                                                                                                                                                                          _Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0x6468b0, _M_refcount = {_M_pi = 0x6468a0}}, <No data fields>}
        path_socket = "/tmp/.ydotool_socket"
        fd_client = 3
        tool_constructor = <optimized out>
        this_tool = 0x646220
        rc = <optimized out>

Thread 1 (Thread 0x63c380 (LWP 502211) "ydotool"):
#0  0x0000000000452edc in __libc_send (fd=3, buf=buf@entry=0x7fffffffe730, len=len@entry=8, flags=flags@entry=0) at ../sysdeps/unix/sysv/linux/send                                                                                                                                                                          .c:28
No locals.
#1  0x000000000040f417 in socket_callback (type=<optimized out>, code=<optimized out>, val=<optimized out>, userp=<optimized out>) at ./Client/ydot                                                                                                                                                                          ool.cpp:81
        buf = {type = 1, code = 56, value = 1}
        fd = <optimized out>
#2  0x00000000004545a4 in uInputPlus::uInput::Emit(unsigned short, unsigned short, int) const ()
No symbol table info available.
#3  0x000000000045460e in uInputPlus::uInput::SendKey(unsigned short, unsigned int, bool) const ()
No symbol table info available.
#4  0x000000000041b2ea in ydotool::Tools::Key::EmitKeyCodes (this=this@entry=0x646220, key_delay=key_delay@entry=100, list_keycodes=...) at ./Tools                                                                                                                                                                          /Key/Key.cpp:101
        it_m = @0x645e80: 56
        __for_range = @0x645ea0: {<std::_Vector_base<int, std::allocator<int> >> = {_M_impl = {<std::allocator<int>> = {<__gnu_cxx::new_allocator<i                                                                                                                                                                          nt>> = {<No data fields>}, <No data fields>}, <std::_Vector_base<int, std::allocator<int> >::_Vector_impl_data> = {_M_start = 0x645e80, _M_finish =                                                                                                                                                                           0x645e8c, _M_end_of_storage = 0x645e8c}, <No data fields>}}, <No data fields>}
        __for_begin = {_M_current = <optimized out>}
        __for_end = {_M_current = <optimized out>}
        it = @0x645ea0: {<std::_Vector_base<int, std::allocator<int> >> = {_M_impl = {<std::allocator<int>> = {<__gnu_cxx::new_allocator<int>> = {<                                                                                                                                                                          No data fields>}, <No data fields>}, <std::_Vector_base<int, std::allocator<int> >::_Vector_impl_data> = {_M_start = 0x645e80, _M_finish = 0x645e8c                                                                                                                                                                          , _M_end_of_storage = 0x645e8c}, <No data fields>}}, <No data fields>}
        __for_range = @0x7fffffffe850: {<std::_Vector_base<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<i                                                                                                                                                                          nt> > > >> = {_M_impl = {<std::allocator<std::vector<int, std::allocator<int> > >> = {<__gnu_cxx::new_allocator<std::vector<int, std::allocator<int                                                                                                                                                                          > > >> = {<No data fields>}, <No data fields>}, <std::_Vector_base<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::all                                                                                                                                                                          ocator<int> > > >::_Vector_impl_data> = {_M_start = 0x645ea0, _M_finish = 0x645eb8, _M_end_of_storage = 0x645eb8}, <No data fields>}}, <No data fie                                                                                                                                                                          lds>}
        __for_begin = {_M_current = <optimized out>}
        __for_end = {_M_current = <optimized out>}
        sleep_time = 50000
#5  0x000000000041c6d2 in ydotool::Tools::Key::Exec (this=0x646220, argc=2, argv=<optimized out>) at ./Tools/Key/Key.cpp:204
        time_delay = 100
        time_keydelay = <optimized out>
        time_repdelay = <optimized out>
        repeats = 0
        file_path = {static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fiel                                                                                                                                                                          ds>}, <No data fields>}, _M_p = 0x7fffffffe950 ""}, _M_string_length = 0, {_M_local_buf = "\000EL_Z\000\000\000\022\001\000\000\023\001\000", _M_al                                                                                                                                                                          located_capacity = 388145890560}}
        extra_args = {<std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx                                                                                                                                                                          11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {_M_impl = {<std::allocator<std::__cxx11::basic_string<char, std::char                                                                                                                                                                          _traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>                                                                                                                                                                           > >> = {<No data fields>}, <No data fields>}, <std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >,                                                                                                                                                                           std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Vector_impl_data> = {_M_start = 0x646730, _M_f                                                                                                                                                                          inish = 0x646750, _M_end_of_storage = 0x646750}, <No data fields>}}, <No data fields>}
        keycodes = {<std::_Vector_base<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >> = {_M_imp                                                                                                                                                                          l = {<std::allocator<std::vector<int, std::allocator<int> > >> = {<__gnu_cxx::new_allocator<std::vector<int, std::allocator<int> > >> = {<No data f                                                                                                                                                                          ields>}, <No data fields>}, <std::_Vector_base<std::vector<int, std::allocator<int> >, std::allocator<std::vector<int, std::allocator<int> > > >::_                                                                                                                                                                          Vector_impl_data> = {_M_start = 0x645ea0, _M_finish = 0x645eb8, _M_end_of_storage = 0x645eb8}, <No data fields>}}, <No data fields>}
#6  0x00000000004098f3 in main (argc=3, argv=0x7fffffffeca8) at ./Client/ydotool.cpp:136
        library_path = <synthetic pointer>
        it_cmd = {<std::__detail::_Node_iterator_base<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > con                                                                                                                                                                          st, void*>, true>> = {_M_cur = <optimized out>}, <No data fields>}
        instance = {<std::__shared_ptr<ydotool::Instance, (__gnu_cxx::_Lock_policy)2>> = {<std::__shared_ptr_access<ydotool::Instance, (__gnu_cxx::                                                                                                                                                                          _Lock_policy)2, false, false>> = {<No data fields>}, _M_ptr = 0x6468b0, _M_refcount = {_M_pi = 0x6468a0}}, <No data fields>}
        path_socket = "/tmp/.ydotool_socket"
        fd_client = 3
        tool_constructor = <optimized out>
        this_tool = 0x646220
        rc = <optimized out>
```

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
